#!/bin/bash

checkfile () {
	file=$1
	step=0
	pn=0
	while read n
	do
		step=$((step+1))
		#echo "Checking $file: $step $n"
		[[ $n == $step ]] || {
			# allow repeats- json!
			[ $n == $pn ] && continue
			echo $file expected $step got $n
			break
			}
		pn=$n
	done
	echo "$file: $step steps"
	}

for f in */*.ipynb
do
	sed -n -e 's/,//' -e 's/.*execution_count": //p' $f | checkfile $f
done

