#!/bin/bash

checkfile () {
	file=$1
	step=0
	pn=0
	while read n
	do
		step=$((step+1))
		#echo "Checking $file: $step $n"
		[[ $n == $step ]] || {
			# allow repeats- json!
			[ $n == $pn ] && continue
			[ $nameonly ] && {
				echo $file
				break
				}
			echo $file expected $step got $n
			break
			}
		pn=$n
	done
	#echo "$file: $step steps"
	}


while getopts af:n opt
do
	case $opt in
	'a')
		all=:
		;;
	'f')
		Files="$OPTARG"
		;;
	'n')
		nameonly=:
		;;
	esac
done

[ "$Files" ] || {
	if [ $all ]
	then
		Files=$(find near rosetta -name '*.ipynb' | fgrep -v '/.')
	else
		Files=$(git ls-files \*.ipynb)
	fi
	}

for f in $Files
do
	sed -n -e 's/,//' -e 's/.*execution_count": //p' $f | checkfile $f
done

