#!/bin/bash -x

File=README.md
URL="https://nbviewer.org/github/earthshrink/anomaly-sim/blob/master/"

sccat -M files.sc | sed \
	-e '2s/.*/|:--|:--|/' \
	-e 's/near\///' \
	-e 's/rosetta\///' \
	-e 's/\(near_[^ ]*\.ipynb\)/[&](_URL_near\/&)/' \
	-e 's/\(rosetta_[^ ]*\.ipynb\)/[&](_URL_rosetta\/&)/' \
	-e "s!_URL_!$URL!" \
	> files.md

sed -i \
	-e '/^|/d' \
	-e '/{{{ table/r files.md' \
	$File

